site_name: Ragnorok Robotics 3748 Swerve
site_url: http://www.example.com
theme:
  name: readthedocs
  logo: logo.png
  favicon: logo.png
  palette:
    scheme: slate
    primary: yellow
nav:
  - Overview: index.md
  - Swerve:
      - Swerve Overview: SwerveDrive/index.md
      - Swerve Math: SwerveDrive/swerveMath.md
      - Logging Workflow: SwerveDrive/logging.md
      - The Module Subsystem: SwerveDrive/moduleSubsystem.md
      - The Drivetrain Subsystem: SwerveDrive/drivetrainSubsystem.md
      - Autonomous Workflow: SwerveDrive/auto.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
