site_name: Ragnorok Robotics 3748 Swerve
site_url: http://www.example.com
theme:
  name: material
  logo: logo.png
  favicon: logo.png
  palette:
    scheme: slate
    primary: yellow
nav:
  - Overview: index.md
  - Swerve:
      - Swerve Overview: SwerveDrive/index.md
      - Swerve Math: SwerveDrive/swerveMath.md
      - The Drivetrain Subsystem: SwerveDrive/drivetrainSubsystem.md
      - Logging Workflow: SwerveDrive/logging.md
      - Autonomous Workflow: SwerveDrive/auto.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
